//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contestanonymizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("contestanonymizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned
        ///Able
        ///Absolute
        ///Adorable
        ///Adventurous
        ///Academic
        ///Acceptable
        ///Acclaimed
        ///Accomplished
        ///Accurate
        ///Aching
        ///Acidic
        ///Acrobatic
        ///Active
        ///Actual
        ///Adept
        ///Admirable
        ///Admired
        ///Adolescent
        ///Adored
        ///Advanced
        ///Afraid
        ///Affectionate
        ///Aged
        ///Aggravating
        ///Aggressive
        ///Agile
        ///Agitated
        ///Agonizing
        ///Agreeable
        ///Ajar
        ///Alarmed
        ///Alarming
        ///Alert
        ///Alienated
        ///Alive
        ///All
        ///Altruistic
        ///Amazing
        ///Ambitious
        ///Ample
        ///Amused
        ///Amusing
        ///Anchored
        ///Ancient
        ///Angelic
        ///Angry
        ///Anguished
        ///Animated
        ///Annual
        ///Another
        ///Antique
        ///Anxious
        ///Any
        ///Appreh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk
        ///Eagle
        ///Harrier
        ///Kite
        ///Osprey
        ///Lark
        ///Kingfisher
        ///Duck
        ///Mallard
        ///Wigeon
        ///Teal
        ///Pintail
        ///Goose
        ///Bufflehead
        ///Merganser
        ///Swift
        ///Heron
        ///Waxwing
        ///Nighthawk
        ///Vulture
        ///Creeper
        ///Dove
        ///Crow
        ///Jay
        ///Magpie
        ///Cuckoo
        ///Blackbird
        ///Sparrow
        ///Bunting
        ///Warbler
        ///Bobolink
        ///Oriole
        ///Finch
        ///Loon
        ///Crane
        ///Catbird
        ///Thrasher
        ///Thrush
        ///Gnatcatcher
        ///Kinglet
        ///Bluebird
        ///Robin
        ///Chickadee
        ///Pelican
        ///Cormorant
        ///Pheasant
        ///Woodpecker
        ///Sapsucker
        ///Coot
        ///Sandpiper
        ///Willet
        ///Snipe
        ///Owl
        ///Starling
        ///Ibis
        ///Hummingbird
        ///Wren
        ///Wood-pewee
        ///Flycatcher
        ///Pho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string birds {
            get {
                return ResourceManager.GetString("birds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting
        ///Accommodating
        ///Afraid
        ///Aggressive
        ///Agitated
        ///Alarmed
        ///Amazed
        ///Amused
        ///Antagonistic
        ///Anxious
        ///Apathetic
        ///Apprehensive
        ///Arrogant
        ///Astonished
        ///Astounded
        ///Attentive
        ///Blase
        ///Bold
        ///Bothered
        ///Brave
        ///Calm
        ///Capable
        ///Casual
        ///Charming
        ///Cheerful
        ///Cheery
        ///Churlish
        ///Collected
        ///Comfortable
        ///Competitive
        ///Composed
        ///Compulsive
        ///Concerned
        ///Confident
        ///Conflicted
        ///Conscientious
        ///Conservative
        ///Considerate
        ///Conspicuous
        ///Contemptible
        ///Content
        ///Convivial
        ///Cool
        ///Courageous
        ///Covetous
        ///Creative
        ///Critical
        ///Curious
        ///Cynical
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emotions {
            get {
                return ResourceManager.GetString("emotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gecko
        ///Chameleon
        ///Iguana
        ///Anole
        ///Dragon
        ///Monitor
        ///Tegu
        ///Skink.
        /// </summary>
        internal static string lizards {
            get {
                return ResourceManager.GetString("lizards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrew
        ///Bat
        ///Jackrabbit
        ///Beaver
        ///Rat
        ///Muskrat
        ///Mouse
        ///Porcupine
        ///Gopher
        ///Dog
        ///Squirrel
        ///Coyote
        ///Fox
        ///Bobcat
        ///Tiger
        ///Lion
        ///Skunk
        ///Weasel
        ///Badger
        ///Raccoon
        ///Chipmunk
        ///Monkey
        ///Gorilla
        ///Lemur
        ///Emu
        ///Kangaroo
        ///Elephant
        ///Opossum
        ///Armadillo
        ///Prairie Dog
        ///Marmot
        ///Vole
        ///Whale
        ///Shrew
        ///Bear
        ///Stoat
        ///Sea Lion
        ///Walrus
        ///Seal
        ///Elk
        ///Pronghorn
        ///Bison
        ///Sheep
        ///Manatee
        ///Dolphin
        ///Unicorn
        ///Zebra
        ///Cheetah.
        /// </summary>
        internal static string mammals {
            get {
                return ResourceManager.GetString("mammals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alligator
        ///Tortoise
        ///Turtle
        ///Crocodile
        ///Rattlesnake
        ///Cottonmouth
        ///Viper.
        /// </summary>
        internal static string reptiles {
            get {
                return ResourceManager.GetString("reptiles", resourceCulture);
            }
        }
    }
}
