//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace contestanonymizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("contestanonymizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandoned
        ///able
        ///absolute
        ///adorable
        ///adventurous
        ///academic
        ///acceptable
        ///acclaimed
        ///accomplished
        ///accurate
        ///aching
        ///acidic
        ///acrobatic
        ///active
        ///actual
        ///adept
        ///admirable
        ///admired
        ///adolescent
        ///adored
        ///advanced
        ///afraid
        ///affectionate
        ///aged
        ///aggravating
        ///aggressive
        ///agile
        ///agitated
        ///agonizing
        ///agreeable
        ///ajar
        ///alarmed
        ///alarming
        ///alert
        ///alienated
        ///alive
        ///all
        ///altruistic
        ///amazing
        ///ambitious
        ///ample
        ///amused
        ///amusing
        ///anchored
        ///ancient
        ///angelic
        ///angry
        ///anguished
        ///animated
        ///annual
        ///another
        ///antique
        ///anxious
        ///any
        ///apprehensive
        ///appropriate
        ///apt
        ///arctic
        ///arid
        ///aromatic
        ///artistic
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hawk
        ///Eagle
        ///Harrier
        ///Kite
        ///Osprey
        ///Lark
        ///Kingfisher
        ///Duck
        ///Mallard
        ///Wigeon
        ///Teal
        ///Pintail
        ///Goose
        ///Bufflehead
        ///Merganser
        ///Swift
        ///Heron
        ///Waxwing
        ///Nighthawk
        ///Vulture
        ///Creeper
        ///Dove
        ///Crow
        ///Jay
        ///Magpie
        ///Cuckoo
        ///Blackbird
        ///Sparrow
        ///Bunting
        ///Warbler
        ///Bobolink
        ///Oriole
        ///Finch
        ///Loon
        ///Crane
        ///Catbird
        ///Thrasher
        ///Thrush
        ///Gnatcatcher
        ///Kinglet
        ///Bluebird
        ///Robin
        ///Chickadee
        ///Pelican
        ///Cormorant
        ///Pheasant
        ///Woodpecker
        ///Sapsucker
        ///Coot
        ///Sandpiper
        ///Willet
        ///Snipe
        ///Owl
        ///Starling
        ///Ibis
        ///Hummingbird
        ///Wren
        ///Wood-pewee
        ///Flycatcher
        ///Phoebe
        ///Vireo.
        /// </summary>
        internal static string birds {
            get {
                return ResourceManager.GetString("birds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accepting
        ///accommodating
        ///afraid
        ///aggressive
        ///agitated
        ///alarmed
        ///amazed
        ///amused
        ///antagonistic
        ///anxious
        ///apathetic
        ///apprehensive
        ///arrogant
        ///astonished
        ///astounded
        ///attentive
        ///blase
        ///bold
        ///bothered
        ///brave
        ///calm
        ///capable
        ///casual
        ///charming
        ///cheerful
        ///cheery
        ///churlish
        ///collected
        ///comfortable
        ///competitive
        ///composed
        ///compulsive
        ///concerned
        ///confident
        ///conflicted
        ///conscientious
        ///conservative
        ///considerate
        ///conspicuous
        ///contemptible
        ///content
        ///convivial
        ///cool
        ///courageous
        ///covetous
        ///creative
        ///critical
        ///curious
        ///cynical
        ///dazzled
        ///debilitated
        ///defensive
        ///dejected
        ///delighted
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emotions {
            get {
                return ResourceManager.GetString("emotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gecko
        ///Chameleon
        ///Iguana
        ///Anole
        ///Dragon
        ///Monitor
        ///Tegu
        ///Skink.
        /// </summary>
        internal static string lizards {
            get {
                return ResourceManager.GetString("lizards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrew
        ///Bat
        ///Jackrabbit
        ///Beaver
        ///Rat
        ///Muskrat
        ///Mouse
        ///Porcupine
        ///Gopher
        ///Dog
        ///Squirrel
        ///Coyote
        ///Fox
        ///Bobcat
        ///Tiger
        ///Lion
        ///Skunk
        ///Weasel
        ///Badger
        ///Raccoon
        ///Chipmunk
        ///Monkey
        ///Gorilla
        ///Lemur
        ///Emu
        ///Kangaroo
        ///Elephant
        ///Opossum
        ///Armadillo
        ///Prairie Dog
        ///Marmot
        ///Vole
        ///Whale
        ///Shrew
        ///Bear
        ///Stoat
        ///Sea Lion
        ///Walrus
        ///Seal
        ///Elk
        ///Pronghorn
        ///Bison
        ///Sheep
        ///Manatee
        ///Dolphin
        ///Unicorn
        ///Zebra
        ///Cheetah.
        /// </summary>
        internal static string mammals {
            get {
                return ResourceManager.GetString("mammals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alligator
        ///Tortoise
        ///Turtle
        ///Crocodile
        ///Rattlesnake
        ///Cottonmouth
        ///Viper.
        /// </summary>
        internal static string reptiles {
            get {
                return ResourceManager.GetString("reptiles", resourceCulture);
            }
        }
    }
}
